### PR TITLE
Redesign Index and Nav

### PR DESCRIPTION
**Pull request by AbhayAysola**

### CODE REVIEW

**Review by ppalone — CHANGES_REQUESTED** [review]
This looks great in Dark mode. But slight lame in light mode given the fact that the default mode when any user visits site is light mode.

**Comment by ppalone** [comment]
But I'm glad that you cleared all --dark prefixes.

**Comment by AbhayAysola** [comment]
All right, thanks for the feedback. I'll try to make it look better.

**Comment by AbhayAysola** [comment]
@ppalone . Can you try reloading the page. For some reason, the light them colors only work if you load the page while in light mode.

**Comment by ppalone** [comment]
@AbhayAysola Can I put this pull request on a hold for somedays?

**Comment by AbhayAysola** [comment]
Sure! It's your repo.

**Pull request closed without merging**
